# Generated by Django 6.0.2 on 2026-05-14 21:35

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=100)),
                ("lugar", models.CharField(max_length=150)),
                ("fecha_evento", models.DateField()),
                ("cupo_maximo", models.PositiveIntegerField()),
                ("servicios", models.TextField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "codigo_invitacion",
                    models.CharField(
                        default=web.models.generar_codigo_unico,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "organizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=100)),
                ("hora_reserva", models.TimeField()),
                ("numero_personas", models.PositiveIntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservaciones",
                        to="web.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
