# Generated by Django 6.0.2 on 2026-04-29 05:39

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_invitacion",
                    models.CharField(
                        default=web.models.generar_codigo_unico,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=200)),
                ("fecha_evento", models.DateField(blank=True, null=True)),
                ("cupo_maximo", models.IntegerField(default=0)),
                ("lugar", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("servicios", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mis_eventos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservacion",
            fields=[
                ("id_reservacion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_cliente", models.CharField(max_length=100)),
                ("numero_personas", models.PositiveIntegerField()),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.evento"
                    ),
                ),
            ],
            options={
                "unique_together": {("evento", "nombre_cliente")},
            },
        ),
    ]
