# Generated by Django 6.0.2 on 2026-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservacion",
            name="hora",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
