# Generated by Django 4.2.10 on 2026-05-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_reservacion_activa_unica"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
